### PR TITLE
Refactor design for help dialog

### PR DESCRIPTION
**Pull request by invaderb**
Refactor design for help dialog
Clean up
IDE additions to .gitignore

Removed broken links and redesign content based on suggestions in the Tak discord 

https://trello.com/c/Bmi5s3xs
https://trello.com/c/Bmi5s3xs

### CODE REVIEW

**Review by NoHatCoder — CHANGES_REQUESTED** [review]
All the `</div></div>` lines were there for a reason, splitting them inserts a whitespace that off-centres the block, and as far as I recall shenanigans with  wrapping can also happen.

An id may not contain whitespace, you have `<div class="tab-content" id="pills-tabContent p-3">`.

Some of the code wastes a lot of vertical space, readability is lost when little code fit on the screen.

**Comment by invaderb** [comment]
@NoHatCoder they are closing divs it's not going to off center the block.  in fact having them on one line makes when when collapse the code block look like you have an extra closing div
Screen Shot 2022-01-20 at 10 41 20 AM

if you run it through pretty much any standard html beautifier it puts them on their own lines.

If this needs to be a standard in this project then possibly adding an editor config to enforce styling might be the way to go.

I cleaned up the html a bit more and got rid of unneeded attributes.

**Comment by NoHatCoder** [comment]
If you come here, break stuff, and then argue that you didn't break it, you are not helping.

**Comment by invaderb** [comment]
@NoHatCoder I apologize if it came off that way I'm in no way trying to arguing that I didn't break anything, if something isn't right please show me I'd be happy to correct it.

I'm not trying to come in here and change everything to how I think it should be, I just have some free time and thought I could help out, I know how it is to work on a project alone without much help. but also coming into a project with little to no background on the history or documentation also has it's challenges.

**Comment by NoHatCoder** [comment]
Well you did argue that you didn't break it, rather than just fixing it.

During review I went through the trouble of screenshotting the site with and without those whitespaces, it is 2 pixels off. Something something vertical centering, I don't recall exactly why the structure ended up being as it is, I just know that what is there is there because it turned out to work, including those non-spaces.

**Comment by invaderb** [comment]
Ok I do see the 2 pixel shift that you are talking about, however I cleared cache and did a hard reload and it went away.

to rule out if it's actually the html did you compare the changes with being logged in on one and not in the other?

I just noticed that if you login and refresh the page it shifts the content up 2 pixels.

**Comment by NoHatCoder** [comment]
What? Logging in and out doesn't change the layout. In any case it is 2 pixels sideways, the space gets to be there because there is a pseudo-element after it.

**Comment by invaderb** [comment]
Actually never mind, there is an inline style top 41px getting added to the notation and chat when adjusting the window size, which was the layout shift I was seeing when comparing playtak.com and my local changes.

With completely cleared cache and cookies I've checked 3 browsers Chrome, Firefox and Safari and don't see any layout shift sideways difference between playtak.com and my local changes, can you share your screenshots?

Here's on firefox
Screen Shot 2022-01-20 at 2 21 07 PM
Screen Shot 2022-01-20 at 2 21 20 PM

**Comment by NoHatCoder** [comment]
I don't have the mental fortitude to keep on replying or thinking about this while you do not do as I ask.

**Comment by invaderb** [comment]
👍

**Comment by invaderb** [comment]
@NoHatCoder will you reopen this PR and I'll make the corrections?

**Comment by invaderb** [comment]
@NoHatCoder those div changes have been reverted.

**Pull request merged**
